### ISSUE TITLE
[AI] Docs for configuring different LLM Providers

### ISSUE THREAD

**Issue by npolshakova** [kgateway-dev/kgateway.dev#231]
Each provider has slightly different configuration semantics, it would be helpful to create a user guide with examples on how to configure each one. 

For example azure endpoint are configured like this:

```yaml
      endpoint: ai-gateway.openai.azure.com
      deploymentName: gpt-4o-mini
      apiVersion: 2024-02-15-preview
```

But our docs don't clarify what should go into `endpoint` (ie. `https://ai-gateway.openai.azure.com` vs `ai-gateway.openai.azure`)

See community slack thread for more context: https://cloud-native.slack.com/archives/C080D3PJMS4/p1749063124343589
